FROM alpine:3.14.0
LABEL maintainer="Nho Luong <luongutnho@hotmail.com>"
RUN echo "testuser:x:10999:10999:,,,:/home/testuser:/bin/bash" >> /etc/passwd && echo "testuser::18761:0:99999:7:::" >> /etc/shadow
